### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by ayotec2015** [deanwilson/terraform-aws-github-ssh-keys#6]
Hi, 

This looks amazing. Is it possible to have more than 1 github user ?   like 3/4 users.

Thanks

**Comment by deanwilson** [comment]
You can have multiple users by calling the resource multiple times with a different module name. If you need github SSH keys these days I'd recommend using the [native terraform github data](https://www.terraform.io/docs/providers/github/d/user.html) rather than my module.
